# Generated by Django 3.0.1 on 2020-01-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
    ]
